development:
  adapter: postgresql
  database: rails_development
  username: sheila
  encoding: unicode
  host: localhost

testing:
  adapter: postgresql
  database: rails_testing
  username: sheila
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: rails_production
  username: sheila
  encoding: unicode