development:
  adapter: postgresql
  database: rails_development
  username: gol
  encoding: unicode
  host: localhost

testing:
  adapter: postgresql
  database: rails_testing
  username: gol
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: rails_production
  username: gol
  encoding: unicode