development:
  adapter: postgresql
  database: griddy_development
  username: gol
  encoding: unicode
  host: localhost

testing:
  adapter: postgresql
  database: griddy_testing
  username: gol
  encoding: unicode
  host: localhost

production:
  adapter: postgresql
  database: griddy_production
  username: gol
  encoding: unicode